name: time-class-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - scipy
  - onnx
  - pip:
      - tensorflow==2.11.1
      - tensorflow-addons==0.23.0
      - keras==2.11.0
      - keras-tcn==3.5.0
      - keras-visualizer==3.1.2
      - opencv-python
      - h5py
      - plotly
      - kaleido
      - visualkeras